compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.0.2.cjs

npmScopes:
  zenobius:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN:-}"
